import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for MyPaperPop by Good Creator LLC.',
  alternates: {
    canonical: '/terms',
  },
};

export default function TermsOfServicePage() {
  return (
    <article className="prose prose-gray max-w-none">
      <h1>Terms of Service</h1>
      <p className="text-sm text-gray-500">Effective Date: February 26, 2026</p>
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of the MyPaperPop website and service operated
        by Good Creator LLC (&quot;MyPaperPop,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) at{' '}
        <strong>mypaperpop.com</strong>. By accessing or using MyPaperPop, you agree to be bound by these Terms.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By creating an account or using MyPaperPop, you confirm that you are at least 18 years old, or that you
        are at least 13 years old (16 in the EEA/UK, 18 in India) and have the consent of a parent or legal guardian.
        If you do not agree to these Terms, do not use the service.
      </p>

      <h2>2. Service Description</h2>
      <p>
        MyPaperPop is an AI-powered service that generates custom coloring page sketches from text descriptions.
        The service is designed for parents and teachers to create printable coloring pages for children. You can
        also upload photos of colored-in pages using the &quot;Color &amp; Show&quot; feature to create a before-and-after
        keepsake.
      </p>
      <p>We offer the following options:</p>
      <ul>
        <li><strong>Free tier</strong> — 3 images per day, no cost</li>
        <li><strong>Coloring page packs</strong> — one-time purchases of extra coloring pages (e.g., 25 pages, 75 pages). Each generated image uses one coloring page. Purchased pages never expire.</li>
      </ul>
      <p>
        Prices are displayed in your local currency where available (e.g., USD, INR, EUR). The final
        price charged is the amount shown at checkout. We reserve the right to modify features, pricing,
        and quotas at any time.
      </p>

      <h2>3. Account Terms</h2>
      <ul>
        <li>You must sign in with a valid Google account to use MyPaperPop.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>You may only maintain one account per person.</li>
        <li>We reserve the right to suspend or terminate accounts that violate these Terms or are used for abusive purposes.</li>
      </ul>

      <h2>4. Payment Terms</h2>
      <ul>
        <li>Coloring page packs are one-time purchases processed through Stripe.</li>
        <li>Purchased pages are added to your account immediately and never expire.</li>
        <li>All purchases of digital coloring pages are final. We do not offer refunds on coloring page pack purchases, as the pages are delivered instantly upon payment.</li>
        <li>Prices are displayed in your local currency where available. The charge amount is the price shown at checkout.</li>
      </ul>

      <h3>EU/EEA Right of Withdrawal</h3>
      <p>
        If you are in the European Economic Area, you have a 14-day right of withdrawal for digital purchases
        under the Consumer Rights Directive. However, by purchasing coloring pages, you acknowledge and agree that the
        digital content is delivered immediately upon payment, and you expressly consent to waive
        your 14-day withdrawal right. This waiver is confirmed at checkout.
      </p>

      <h2>5. AI-Generated Content &amp; User-Uploaded Content</h2>
      <ul>
        <li>Coloring pages are generated by artificial intelligence (AI) based on your text prompts.</li>
        <li>We do not guarantee the quality, accuracy, or appropriateness of AI-generated content.</li>
        <li>AI outputs may occasionally produce unexpected or unintended results. We recommend that parents and teachers review all generated content before sharing it with children.</li>
        <li>We continuously work to improve output quality but make no warranties regarding specific results.</li>
        <li>You may upload photos of your colored-in pages via the &quot;Color &amp; Show&quot; feature. When you do, we will process your photo (crop, enhance colors, resize) and generate a side-by-side composite image that includes &quot;Made with MyPaperPop&quot; branding.</li>
        <li>You retain ownership of photos you upload. By uploading a photo, you grant MyPaperPop a non-exclusive, worldwide license to store, process, display, and distribute the photo and any composite images derived from it for the purpose of providing the service.</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <ul>
        <li>
          <strong>Your content</strong> — You retain ownership of the text prompts you submit and any photos you
          upload. You are granted a personal, non-exclusive, non-transferable license to use the coloring page
          images generated from your prompts for personal, non-commercial use (including printing and sharing with
          children, students, or family). Composite images created from your uploaded photos via Color &amp; Show
          are licensed under the same terms.
        </li>
        <li>
          <strong>Our platform</strong> — MyPaperPop, including its design, code, branding, and underlying technology,
          is the intellectual property of Good Creator LLC. You may not copy, modify, distribute, or reverse-engineer
          any part of the platform.
        </li>
      </ul>

      <h2>7. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit prompts intended to generate violent, sexual, hateful, or illegal content</li>
        <li>Use the service to create content that infringes on the intellectual property rights of others</li>
        <li>Attempt to circumvent usage limits, quotas, or security measures</li>
        <li>Use automated tools, bots, or scripts to access the service</li>
        <li>Interfere with or disrupt the service or its infrastructure</li>
        <li>Upload photos that contain inappropriate content, personal information of others, or material you do not have the right to share</li>
        <li>Use the service for any unlawful purpose</li>
      </ul>
      <p>
        We reserve the right to remove content and suspend accounts that violate this policy without notice.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, MyPaperPop and Good Creator LLC shall not be liable for any
        indirect, incidental, special, consequential, or punitive damages arising from your use of or inability
        to use the service.
      </p>
      <p>
        Our total liability for any claim arising from these Terms or your use of the service shall not exceed
        the lesser of the amount you paid us in the twelve (12) months preceding the claim, or $50 USD.
      </p>
      <p>
        Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law,
        including liability for fraud, death, or personal injury caused by negligence.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        The service is provided <strong>&quot;as is&quot;</strong> and <strong>&quot;as available&quot;</strong> without
        warranties of any kind, either express or implied, including but not limited to implied warranties of
        merchantability, fitness for a particular purpose, and non-infringement.
      </p>
      <p>
        We do not warrant that the service will be uninterrupted, error-free, or secure, or that any defects
        will be corrected.
      </p>

      <h2>10. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Good Creator LLC, its officers, and employees from any claims,
        damages, losses, or expenses (including reasonable attorney&apos;s fees) arising from your use of the
        service or violation of these Terms. This section does not apply to the extent prohibited by applicable law.
      </p>

      <h2>11. Dispute Resolution</h2>
      <p>
        <strong>Informal Resolution First:</strong> Before filing any formal claim, you agree to contact us at{' '}
        <a href="mailto:goodcreatorllc@gmail.com">goodcreatorllc@gmail.com</a> and attempt to resolve the dispute
        informally for at least 30 days.
      </p>
      <p>
        <strong>Binding Arbitration:</strong> If informal resolution fails, any dispute arising from or relating to
        these Terms or the service shall be resolved by binding arbitration administered by JAMS under its Streamlined
        Arbitration Rules, conducted in Sacramento, California, USA. The arbitrator&apos;s decision shall be final and
        binding.
      </p>
      <p>
        <strong>Class Action Waiver:</strong> You agree that any dispute resolution proceeding will be conducted only on
        an individual basis and not as a class, consolidated, or representative action.
      </p>
      <p>
        <strong>Exceptions:</strong> Either party may seek injunctive or other equitable relief in any court of competent
        jurisdiction. EU/EEA consumers may bring claims in their local courts. This arbitration clause does not apply
        where prohibited by law.
      </p>

      <h2>12. Termination</h2>
      <p>
        We may terminate or suspend your access to the service at any time, with or without cause, with or without
        notice. Upon termination, your right to use the service ceases immediately. You may delete your account
        at any time from the Account settings page.
      </p>

      <h2>13. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes by posting the
        updated Terms on this page and updating the &quot;Effective Date&quot; above. For material changes,
        we will provide at least 30 days&apos; notice before the new terms take effect. Your continued use of the
        service after changes are posted constitutes acceptance of the updated Terms.
      </p>

      <h2>14. Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of the State of California,
        without regard to its conflict-of-law provisions. If you are an EU/EEA consumer, you retain the benefit
        of any mandatory consumer protection provisions of your country of residence.
      </p>

      <h2>15. Severability</h2>
      <p>
        If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent
        jurisdiction, the remaining provisions shall remain in full force and effect. The invalid provision will be
        modified to the minimum extent necessary to make it valid and enforceable while preserving its original intent.
      </p>

      <h2>16. Entire Agreement</h2>
      <p>
        These Terms, together with our <a href="/privacy">Privacy Policy</a>, constitute the entire agreement
        between you and Good Creator LLC regarding the use of MyPaperPop and supersede all prior agreements,
        understandings, and communications, whether written or oral.
      </p>

      <h2>17. Force Majeure</h2>
      <p>
        We shall not be liable for any failure or delay in performing our obligations under these Terms where such
        failure or delay results from circumstances beyond our reasonable control, including but not limited to
        natural disasters, acts of government, internet outages, power failures, third-party service provider
        outages, or cyberattacks.
      </p>

      <h2>18. Contact Us</h2>
      <p>If you have questions about these Terms, contact us at:</p>
      <ul>
        <li><strong>Email:</strong> <a href="mailto:goodcreatorllc@gmail.com">goodcreatorllc@gmail.com</a></li>
        <li><strong>Company:</strong> Good Creator LLC</li>
        <li><strong>Address:</strong> 1401 21st ST #15039, Sacramento, CA 95811, USA</li>
      </ul>
    </article>
  );
}
