packages:
  - "."

overrides:
  esbuild: 0.28.1
  postcss: 8.5.15
  sharp: ^0.35.2

allowBuilds:
  '@tailwindcss/oxide': true
  braintrust: true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
