import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    POSTGRES_URL: z.string().min(1),
    AUTH_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    STRIPE_SECRET_KEY: z.string().min(1),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    BASE_URL: z.string().url(),
    AWS_ENDPOINT_URL: z.string().url(),
    AWS_ACCESS_KEY_ID: z.string().min(1),
    AWS_SECRET_ACCESS_KEY: z.string().min(1),
    AWS_S3_BUCKET_NAME: z.string().min(1).optional(),
    AWS_DEFAULT_REGION: z.string().min(1).optional(),
    XAI_API_KEY: z.string().min(1),
    GEMINI_API_KEY: z.string().min(1),
    RESEND_API_KEY: z.string().optional(),
    FEEDBACK_EMAIL_TO: z.string().email().optional(),
    AXIOM_DATASET: z.string().optional(),
    AXIOM_TOKEN: z.string().optional(),
    BRAINTRUST_API_KEY: z.string().optional(),
    BRAINTRUST_PROJECT_NAME: z.string().optional(),
    DEV_COUNTRY: z.string().length(2).optional(),
    TEST_AUTH_SECRET: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
  },
  runtimeEnv: {
    POSTGRES_URL: process.env.POSTGRES_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    BASE_URL: process.env.BASE_URL,
    AWS_ENDPOINT_URL: process.env.AWS_ENDPOINT_URL,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
    AWS_DEFAULT_REGION: process.env.AWS_DEFAULT_REGION,
    XAI_API_KEY: process.env.XAI_API_KEY,
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    FEEDBACK_EMAIL_TO: process.env.FEEDBACK_EMAIL_TO,
    AXIOM_DATASET: process.env.AXIOM_DATASET,
    AXIOM_TOKEN: process.env.AXIOM_TOKEN,
    BRAINTRUST_API_KEY: process.env.BRAINTRUST_API_KEY,
    BRAINTRUST_PROJECT_NAME: process.env.BRAINTRUST_PROJECT_NAME,
    DEV_COUNTRY: process.env.DEV_COUNTRY,
    TEST_AUTH_SECRET: process.env.TEST_AUTH_SECRET,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
  },
  skipValidation:
    process.env.NEXT_PHASE === 'phase-production-build' ||
    process.env.SKIP_ENV_VALIDATION === 'true',
  emptyStringAsUndefined: true,
});
